#!/usr/bin/env python3
"""
Generate individual drug pages for SgTxGNN Jekyll site.

This script reads the prediction data and generates markdown files
for each drug in the _drugs collection.
"""

import json
from datetime import date
from pathlib import Path

import pandas as pd


def slugify(text: str) -> str:
    """Convert text to URL-friendly slug."""
    return (
        text.lower()
        .replace(" ", "-")
        .replace("_", "-")
        .replace("/", "-")
        .replace("\\", "-")
        .replace("(", "")
        .replace(")", "")
        .replace(",", "")
        .replace("'", "")
    )


def generate_drug_page(drug_data: dict, output_dir: Path, nav_order: int) -> None:
    """Generate a single drug page."""
    drug_name = drug_data["drug_name"]
    drugbank_id = drug_data["drugbank_id"]
    slug = slugify(drug_name)
    today = date.today().isoformat()

    # Generate indication rows
    indication_rows = []
    for ind in drug_data.get("top_indications", [])[:10]:
        disease = ind.get("disease_name", "Unknown")
        source = ind.get("source", "KG")
        indication_rows.append(f"| {disease} | TxGNN Knowledge Graph | L5 |")

    indications_table = "\n".join(indication_rows) if indication_rows else "| *Evidence collection in progress* | - | - |"

    # Create markdown content
    content = f"""---
layout: default
title: {drug_name}
parent: Drugs
nav_order: {nav_order}
last_modified_date: {today}
---

# {drug_name}

{{: .warning }}
> **Disclaimer**: These predictions are for research purposes only. They do not constitute medical advice and require clinical validation.

## Overview

| Property | Value |
|----------|-------|
| Drug Name | {drug_name} |
| DrugBank ID | [{drugbank_id}](https://go.drugbank.com/drugs/{drugbank_id}) |
| HSA Status | Registered with Health Sciences Authority |
| KG Predictions | {drug_data.get("kg_predictions", 0)} |
| DL Predictions (≥0.7) | {drug_data.get("dl_predictions", 0)} |

## Predicted Indications

The following indications are predicted based on TxGNN knowledge graph analysis:

| Indication | Source | Evidence |
|------------|--------|----------|
{indications_table}

## Evidence Summary

- [Search ClinicalTrials.gov](https://clinicaltrials.gov/search?term={drug_name.replace(" ", "+")})
- [Search PubMed](https://pubmed.ncbi.nlm.nih.gov/?term={drug_name.replace(" ", "+")})
- [View on DrugBank](https://go.drugbank.com/drugs/{drugbank_id})

## External Resources

- [DrugBank: {drug_name}](https://go.drugbank.com/drugs/{drugbank_id})
- [PubChem](https://pubchem.ncbi.nlm.nih.gov/#query={drug_name.replace(" ", "+")})
- [Wikipedia](https://en.wikipedia.org/wiki/{drug_name.replace(" ", "_")})

---

*Generated by SgTxGNN on {today}*
"""

    # Write file
    output_file = output_dir / f"{slug}.md"
    output_file.write_text(content, encoding="utf-8")


def main():
    """Main function to generate all drug pages."""
    # Paths
    project_root = Path(__file__).parent.parent
    data_dir = project_root / "data" / "processed"
    output_dir = project_root / "docs" / "_drugs"

    # Ensure output directory exists
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load prediction data
    kg_file = data_dir / "repurposing_candidates.csv"
    dl_file = data_dir / "txgnn_dl_predictions.csv"

    if not kg_file.exists():
        print(f"Error: {kg_file} not found")
        return

    # Read KG predictions
    print(f"Reading {kg_file}...")
    kg_df = pd.read_csv(kg_file)

    # Determine column names
    drug_col = "ingredient" if "ingredient" in kg_df.columns else "drug_name"
    disease_col = "potential_indication" if "potential_indication" in kg_df.columns else "disease_name"

    # Aggregate by drug
    drug_kg_stats = (
        kg_df.groupby(["drugbank_id", drug_col])
        .agg(
            kg_predictions=(disease_col, "count"),
            top_diseases=(disease_col, lambda x: list(x.head(10))),
        )
        .reset_index()
    )

    # Read DL predictions if available
    dl_stats = {}
    if dl_file.exists():
        print(f"Reading {dl_file}...")
        dl_df = pd.read_csv(dl_file)
        # Filter high confidence predictions
        if "probability" in dl_df.columns:
            dl_high = dl_df[dl_df["probability"] >= 0.7]
            dl_stats = dl_high.groupby("drugbank_id").size().to_dict()
        elif "txgnn_score" in dl_df.columns:
            dl_high = dl_df[dl_df["txgnn_score"] >= 0.7]
            dl_stats = dl_high.groupby("drugbank_id").size().to_dict()

    # Generate pages
    print(f"Generating {len(drug_kg_stats)} drug pages...")

    for idx, row in enumerate(drug_kg_stats.itertuples(), start=1):
        drugbank_id = row.drugbank_id
        drug_name = getattr(row, drug_col)

        # Get DL predictions count
        dl_count = dl_stats.get(drugbank_id, 0)

        # Prepare top indications
        top_indications = [
            {"disease_name": d, "source": "KG"} for d in row.top_diseases
        ]

        drug_data = {
            "drug_name": drug_name.upper(),
            "drugbank_id": drugbank_id,
            "kg_predictions": int(row.kg_predictions),
            "dl_predictions": int(dl_count),
            "top_indications": top_indications,
        }

        generate_drug_page(drug_data, output_dir, idx)

    print(f"\nDone! Generated {len(drug_kg_stats)} drug pages in {output_dir}")


if __name__ == "__main__":
    main()
